apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: s3-sink-connector
  namespace: strimzi-kafka
  labels:
    strimzi.io/cluster: connect-cluster
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 1
  config:
    topics: inventory-stream.public.customers
    s3.bucket.name: "kafka-on-kubernetes"
    s3.region: "eu-central-1"
    flush.size: "5"
    storage.class: io.confluent.connect.s3.storage.S3Storage
    format.class: io.confluent.connect.s3.format.json.JsonFormat
    schema.compatibility: NONE

    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: "false"
